# Site settings
title: Mohamed Almaken
description: Mobile App Developer | Flutter Developer
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mohamed Almaken
user_title: Mobile App Developer
email: m7mdmaken@gmail.com
# twitter_username: lorem_ipsum
# instagram_username:
# facebook_username:
linkedin_username: m7mdalmaken
github_username: m7mdmaken
# medium_username:
# medium_url:
# gplus_username:

exclude: ["package.json", "src", "node_modules", "vendor"]

cv_content: |
  {% capture cv_file %}{% include_relative cv.md %}{% endcapture %}
  {{ cv_file | strip }}
